language: java
before_install:
- openssl aes-256-cbc -K $encrypted_12a8d6dae678_key -iv $encrypted_12a8d6dae678_iv
  -in settings.xml.enc -out settings.xml -d
- mv settings.xml ~/.m2/settings.xml
after_success:
- mvn deploy
